### PR TITLE
Testrun multiple build targets.

### PR DESCRIPTION
**Pull request by bjompen**
The goal is to get a PR to be built and tested on both Windows and Linux platforms. Since this workflow triggers on PR, I kind of need this open to test it.

### CODE REVIEW

**Comment by bjompen** [comment]
FYI: This works now. merge to main and tests will be run on windows and linux.

**Review by StefanIvemo — APPROVED** [review]
LGTM

**Comment by StefanIvemo** [comment]
Unable to merge. Build waiting.

**Comment by bjompen** [comment]
I don't have access to change branch policies. I _think_ we need to change the branch policies to allow force push and then reset the required approvals to those with new names.

**Comment by StefanIvemo** [comment]
> I don't have access to change branch policies. I _think_ we need to change the branch policies to allow force push and then reset the required approvals to those with new names.

@bjompen when can we look at this together?

**Comment by SimonWahlin** [comment]
I like this, but it should really use a matrix containing the OS instead of repeating the code twice.
See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by StefanIvemo** [comment]
Closing this for now, lets investigate using matrix and open a new pr

**Pull request closed without merging**
