### PR TITLE
Markdown update for `-ProgressAction` and missing command

### PR DESCRIPTION
**Pull request by PalmEmanuel**
# Contributing a Pull Request

## Overview/Summary

Updates markdown documentation to take the new common parameter `-ProgressAction` into account, and adds markdown help for new command `Get-UsedModulesInBicepFile`.

Note: Some whitespace is changed around in the parameter blocks because of the fix script I use to manually move the parameter `-ProgressAction`.

## This PR fixes

- #327

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/PSBicep/PSBicep/pulls)
- [X] Associated it with relevant [issues](https://github.com/PSBicep/PSBicep/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/PSBicep/PSBicep/tree/main)
- [X] Performed testing.
- [X] Verified build scripts work.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by PalmEmanuel** [comment]
Some files had `powershell` as the language for the code blocks. If we want to keep that I can go through all of them and add it, but the next time we run the platyPS update in full it's going to overwrite it again.

**Comment by StefanIvemo** [comment]
> Some files had `powershell` as the language for the code blocks. If we want to keep that I can go through all of them and add it, but the next time we run the platyPS update in full it's going to overwrite it again.

We added that to make the docs look better on github. But I guess  that it's not that common to go there to read it. I can live without the highlighting to simplify managing docs.

**Comment by bjompen** [comment]
Was bored. Tried to catch up with y'alls sudden development adventures yesterday. Fixed the merge conflict 😁

**Review by SimonWahlin — APPROVED** [review]
Great work!

**Pull request merged**
